spring.application.name: tasks-ms
spring.profiles.active: local

info:
  app.name: ${spring.application.name}
  app.version: LOCAL

server:
  port: 4020

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: "*"
    enabled-by-default: false
  endpoint:
    beans:
      enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    shutdown:
      enabled: true
